### ISSUE TITLE
fix port to resolve docker unhealthy status

### ISSUE THREAD

**Issue by jzahraoui** [dmcallejo/xTeVe#1]
hello,

can you please fix port in docker file.
I tried to make a pull request but can't do it.

**Comment by dmcallejo** [comment]
Hello,
First let me apologize because I have not been notified about this issue in my email, which is weird.
I have no Idea why you can't do a pull request, that's weird too.

I will look into the issue, although I have no idea why the healthcheck is failing as I daily use the image without any issues.

Sorry again.
